name: airline_project_env
channels:
  - conda-forge
  - defaults
dependencies:
  - altair==5.2.0
  - conda
  - jupyterlab==4.1.0
  - matplotlib==3.8.2
  - numpy==1.26.4
  - pandas==2.2.0
  - python==3.12.1
  - scikit-learn==1.4.0